<?php
// $Id: imagecache_textactions.module,v 1.1.2.2 2010/02/13 01:40:35 dman Exp $
/**
 * @file Provide text manipulation process for imagecache.
 * 
 * Ported by dman 
 * from http://drupal.org/node/264862#comment-865490 by patrickharris
 * 
 */
  cache_clear_all('imagecache_actions', 'cache');
// For simple color routines
module_load_include('inc', 'imagecache_textrender', '../utility');

/**
* Implementation of hook_imagecache_actions().
*/ 
function imagecache_textactions_imagecache_actions() {
  $actions = array(
    'textactions_text2canvas' => array(
      'name' => t('Text'),
      'description' => t('Add static or dynamic (coded) text to an image.'),
      'file' => 'textactions.inc',
    ),
  );

  return $actions;
}

/**
 * Experimental diagnostic page to assist locating valid fonts on the system.
 * Only tuned for Ubuntu so far. I've been unable do find ubiquitous tools that
 * provide useful font listings.'
 */
function imagecache_textactions_help($path, $arg) {
  switch ($path) {
    case 'admin/help#imagecache_textactions':
      $output = "<p>
        For text rendering to work on a server, we <em>must</em>
        know the system path to the font <em>file</em>, not just the name.
        Font library handling differs too much on different systems and
        the available PHP toolkits are unable to return good diagnostics.
        </p><p>
        On Debian/Ubuntu, you may find your fonts in and under
        <code>/usr/share/fonts/truetype/</code>
        eg <code>'/usr/share/fonts/truetype/ttf-bitstream-vera/VeraMono.ttf'</code>
        </p><p>
        On OSX, they are probably in <code>/Library/Fonts/</code>
        eg <code>'/Library/Fonts/Times New Roman Bold Italic.ttf'</code>
        </p><p>
        On Windows, they are probably in <code>C://WINDOWS/Fonts/</code>
        eg <code>'C://WINDOWS/Fonts/comic.TTF'</code>
        </p><p>
        Of course, this will change if you deploy to a different server!
        so the best approach is to place your own TTF font file inside your
        <em>files</em> directory and use that. 
        Just give the filename with no path and it should be found..
        </p>
      ";
      $output .= t("<p>Files directory is !files</p>", array('!files' => file_directory_path()));
      if (ini_get('safe_mode')) {
        $output .= t("<p>
          It appears PHP 'safe mode' is on. 
          This prevents me for knowing which fonts are on your system. 
          You will have to know the exact path and filename of the fonts you intend to use 
          - or upload some *.ttf files to your 'files' directory and use them from there.
        </p>");
      }
      else {
        $list = `find /usr/share/fonts -name \*.ttf`;
        $output .= "<p>Fonts Found : <pre>" . $list . "</pre></p>";
      }
 
      return $output;
      break;
  }
}

/**
 * Need to register the theme functions we expect to use
 */
function imagecache_textactions_theme() {
  return array(
    'textactions_text2canvas' => array(
      'file'      => 'textactions.inc',
      'arguments' => array('element' => NULL),
    ),
    'imagecacheactions_rgb_form' => array(
      'file'      => '../utility.inc',
      'arguments' => array('form' => NULL),
    ),
    'imagecacheactions_rgb' => array(
      'file'      => '../utility.inc',
      'arguments' => array('rgb' => NULL),
    ),
  );
}


