<?php
// $Id: custom_m2m.module,v 1.236.2.3 2011/04/14 10:09:19 Tanzeel Exp $
function custom_m2m_menu(){
  $items['add_modules'] = array(
    'description' => 'Add Devices',
    'page callback' => 'custom_m2m_add_module_page',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'title' => ''
  );
  $items['company_contacts'] = array(
    'description' => 'Company Contacts',
    'page callback' => 'custom_m2m_company_contacts',
    'access arguments' => array('administer users'),
    'type' => MENU_CALLBACK,
    'title' => 'Company Contacts'
  );
  //$items['']
  return $items;
}

function custom_m2m_company_contacts(){
  $query = "SELECT 
      content_field_company.field_company_value AS company,
      users.name AS name,
      users_roles.rid AS role,
      users.uid AS uid
    FROM {node} node 
    INNER JOIN {content_field_company} content_field_company ON content_field_company.nid = node.nid
    INNER JOIN {users} users ON node.uid = users.uid
    LEFT JOIN {users_roles} users_roles ON users_roles.uid = users.uid
    WHERE node.type in ('profile')
    ORDER BY company ASC";
  $header = array(
    array('data' => t('Company')),
    array('data' => t('Company Users')),
    array('data' => t('Sales Reps')),
  );
  $q = db_query($query);
  $companies = content_allowed_values(content_fields('field_company'));
  foreach($companies as $c){
    $rows[$c] = array('company' => $c, 'users' => array(), 'sales' => array());
  }
  while ($r = db_fetch_array($q)) {
    if(!isset($rows[$r['company']])){
      $rows[$r['company']] = array('company' => $r['company'], 'users' => array(), 'sales' => array());
    }
    if($r['role'] == 3){
      $rows[$r['company']]['sales'][] = l($r['name'], 'user/'.$r['uid']);
    }else{
      $rows[$r['company']]['users'][] = l($r['name'], 'user/'.$r['uid']);
    }
  }
  foreach($rows as &$r){
    $r['users'] = implode(', ', $r['users']);
    $r['sales'] = implode(', ', $r['sales']);
  }
  asort($rows);
  return theme('table', $header, $rows);
}

function custom_m2m_content_allowed_values_alter(&$allowed_values, $field) {
  if($field['field_name'] == 'field_featured_cell_chipset' || $field['field_name'] == 'field_rout_chipset_model'){
    $allowed_values = content_allowed_values(content_fields('field_chipset_model'));
  }elseif($field['field_name'] == 'field_featured_conn_chipset'){
    $allowed_values = content_allowed_values(content_fields('field_conn_chipset_model'));
  }
}

function custom_m2m_views_api(){
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'custom_m2m') . '/inc'
  );
}

function custom_m2m_add_module_page(){
    return "Please select the type of device you'd like to create.";
}

function custom_m2m_form_views_exposed_form_alter(&$form, &$form_state) {
  /*
  if(in_array($form['#id'], array('views-exposed-form-router-search-page-1', 'views-exposed-form-featured-products-page-1'))){
    $form['submit']['#value'] = 'Search for Device';
  }else{
    */
    $form['submit']['#value'] = 'Apply Filters';
  //}
  /*
  $show_view_all = FALSE;
  if($form_state['input'] && !empty($form_state['input'])){
    foreach($form_state['input'] as $val){
      if(!empty($val) && is_array($val)){
        $show_view_all = TRUE;
      }
    }
  }
  $form['view_all'] = array('#type' => 'markup', '#value' => '<input style="'.(!$show_view_all ? 'display:none;' : '').'" id="view-all" class="form-submit" type="button" value="View All" onClick="var form = $jq(this).closest(\'form\');  form.find(\'input:checked\').removeAttr(\'checked\'); form.submit();return false;">');
  drupal_add_js(drupal_get_path('theme', 'm2m2') . '/js/show_view_all.js', 'theme');
  drupal_add_js(drupal_get_path('theme', 'm2m2') . '/js/jquery.multiselect.min.js', 'theme');
  drupal_add_js(drupal_get_path('theme', 'm2m2') . '/js/multiselect_init.js', 'theme');
  */
  if(isset($form['field_company_value_many_to_one'])){
    $filters = $form_state['view']->display_handler->get_option('filters');
    $node_type = reset($filters['type']['value']);
    if($node_type == 'featured_product'){
      $node_type_additional = 'router';
    }
    $company_query = 'SELECT DISTINCT(field_company_value) FROM {content_field_company} company INNER JOIN {node} node ON company.vid=node.vid WHERE node.type IN ('.(isset($node_type_additional) ? '"%s", ' : "").'"%s") AND node.status=1 ORDER BY field_company_value;';
    if(isset($node_type_additional)){
      $companies = db_query($company_query, $node_type, $node_type_additional);
    }else{
      $companies = db_query($company_query, $node_type);
    }
    $form['field_company_value_many_to_one']['#options'] = array();
    while ($val = db_fetch_array($companies)) {
      $form['field_company_value_many_to_one']['#options'][$val['field_company_value']] = $val['field_company_value'];
    }
    $form['field_company_value_many_to_one']['#size'] = count($form['field_company_value_many_to_one']['#options']);
  }
}

function custom_m2m_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks[0]['info'] = t('Logged In User Options');
      return $blocks;
    case 'view':
      global $user;
      //if(arg(0) == 'node'){
      //  $node = node_load(arg(1));
      //}
      $block[0]['content'] = '';
      //if((arg(0)=='user') || (arg(0)=='user' && arg(1)==$user->uid && $user->uid!=0) || (strpos($_SERVER['REQUEST_URI'],"manage/device")!==false) || (!empty($node) && $node->type=='profile') || (strpos($_SERVER['REQUEST_URI'],"manage/owndevice")!==false)){
      $display_content_tabs = FALSE;
      
      if(in_array('Sales Rep', $user->roles) && !in_array('administrator', $user->roles)){
        $device_url="manage/device";
      }else{
        $device_url="managedevice";
      }
      $arg0 = arg(0);
      if(!in_array('administrator', $user->roles) && $arg0 == 'user'){
        drupal_goto($device_url);
      }
      
      elseif(strpos($_SERVER['REQUEST_URI'], "node/add/device")!==false){
        $display_content_tabs = TRUE;
        $act3=' class="active"';
      }
      elseif(strpos($_SERVER['REQUEST_URI'], "node/add/connectivity-module")!==false){
        $display_content_tabs = TRUE;
        $act6=' class="active"';
      }
      elseif(strpos($_SERVER['REQUEST_URI'], "node/add/router")!==false){
        $display_content_tabs = TRUE;
        $act7=' class="active"';
      }
      elseif(strpos($_SERVER['REQUEST_URI'], "node/add/computing")!==false){
        $display_content_tabs = TRUE;
        $act12=' class="active"';
      }
      elseif(strpos($_SERVER['REQUEST_URI'], "node/add/featured-product")!==false){
        $display_content_tabs = TRUE;
        $act8=' class="active"';
      }
      elseif(strpos($_SERVER['REQUEST_URI'], "add_modules")!==false){
        $display_content_tabs = TRUE;
        $act9=' class="active"';
      }
      //elseif((strpos($_SERVER['REQUEST_URI'], "user/".$user->uid)!==false || strpos($_SERVER['REQUEST_URI'], "user")!==false) && arg(2)=='') $act1=' class="active"';
      elseif(strpos($_SERVER['REQUEST_URI'], "manage/device")!==false && arg(2)=='') $act4=' class="active"';
      elseif(strpos($_SERVER['REQUEST_URI'], "managedevice")!==false && arg(1)=='') $act4=' class="active"';
      elseif(strpos($_SERVER['REQUEST_URI'], "manage/owndevice")!==false && arg(2)=='') $act5=' class="active"';
      elseif(strpos($_SERVER['REQUEST_URI'], "manage/featured")!==false && arg(2)=='') $act11=' class="active"';
      elseif(strpos($_SERVER['REQUEST_URI'], "company_contacts")!==false && arg(1)=='') $act13=' class="active"';
      elseif(strpos($_SERVER['REQUEST_URI'], "company_module_options")!==false){
        $act10 = ' class="active"';
        $company_list_device_type = arg(1);
        if(!empty($company_list_device_type)){
          ${'act'.$company_list_device_type} = ' class="active"';
        }
      }

      //if($user_fields->roles[3]=='Sales Rep')
      //$device_url1="manage/owndevice";
      //else
      //if($user_fields->roles[3]=='Sales Rep'){
      //  $device_url="manage/device";
      //}else{
      //  $device_url="managedevice";
      //}
      //$block[0]['content'] .= '<ul class="tabs primary"><li'.$act1.'>'.l('View', 'user/'.$user->uid).'</li><li'.$act2.'>'.l('Update Profile', 'user/'.$user->uid.'/edit').'</li>';
      $block[0]['content'] .= '<ul class="tabs primary">';
      
      if(in_array('Sales Rep', $user->roles) && !in_array('administrator', $user->roles)){
        $block[0]['content'] .= '<li'.$act5.'>'.l('Approve Devices', 'manage/owndevice').'</li>';
        $device_url="manage/device";
      }elseif(in_array('administrator', $user->roles)){
        $block[0]['content'] .= '<li'.$act5.'>'.l('Approve Devices', 'manage/owndevice').'</li>';
      }else{
        $device_url="managedevice";
      }
      if($display_content_tabs == TRUE){
        $act9=' class="active"';
      }
      $block[0]['content'] .= '<li'.$act9.'>'.l('Add Devices', 'add_modules').'</li>';
      $block[0]['content'] .= '<li'.$act4.'>'.l('Manage Devices', $device_url).'</li>';
      if(in_array('administrator', $user->roles)){
        $block[0]['content'] .= '<li'.$act11.'>'.l('Manage Featured Products', 'manage/featured').'</li>';
        $block[0]['content'] .= '<li'.$act10.'>'.l('Company Options', 'company_module_options').'</li>';
        $block[0]['content'] .= '<li'.$act13.'>'.l('Company Contacts', 'company_contacts').'</li>';
      }
      $block[0]['content'] .= '</ul>';
        
      if($display_content_tabs == TRUE){
        $profile = content_profile_load('profile', $user->uid);
        $user_companies = array_map(create_function('$c', 'return $c["value"];'), $profile->field_company);
        $is_admin = in_array('administrator', $user->roles);
        $add_devices_ul = '';
        if($is_admin || array_intersect($user_companies, variable_get('m2m_company_list_device', array()))){
          $add_devices_ul .= '<li'.$act3.'>'.l('Add Cellular Module', 'node/add/device').'</li>';
        }
        if($is_admin || array_intersect($user_companies, variable_get('m2m_company_list_connectivity_module', array()))){
          $add_devices_ul .= '<li'.$act6.'>'.l('Add Connectivity Module', 'node/add/connectivity-module').'</li>';
        }
        if($is_admin || array_intersect($user_companies, variable_get('m2m_company_list_router', array()))){
          $add_devices_ul .= '<li'.$act7.'>'.l('Add Wireless Gateway/Router', 'node/add/router').'</li>';
        }
        /*
        if($is_admin || array_intersect($user_companies, variable_get('m2m_company_list_computing', array()))){
          $add_devices_ul .= '<li'.$act12.'>'.l('Add Computing Module', 'node/add/computing').'</li>';
        }
        */
        if($is_admin){
          $add_devices_ul .= '<li'.$act8.'>'.l('Add Featured Product', 'node/add/featured-product').'</li>';
        }
        if(!empty($add_devices_ul)){
          $block[0]['content'] .= '<ul class="tabs secondary">'.$add_devices_ul.'</ul>';
        }else{
          $block[0]['content'] .= '<div style="color:#4D7204;font-style:italic;padding:10px 0;">No device types are currently available to you.  Please contact M2M for assistance.';
        }
      }
      if(isset($company_list_device_type) && !empty($company_list_device_type)){
        $block[0]['content'] .= '<ul class="tabs secondary">';
        $company_list_types = company_list_get_company_types();
        foreach($company_list_types as $company_value => $company_name){
          $block[0]['content'] .= '<li'.${'act'.$company_value}.'>'.l($company_name, 'company_module_options/'.$company_value).'</li>';
        }
        $block[0]['content'] .= '</ul>';
      }
      //}else{
      //  if ($tabs): $block[0]['content'] .= '<ul class="tabs primary">'. $tabs .'</ul></div>'; endif;
          //if ($tabs2): print '<ul class="tabs secondary">'. $tabs2 .'</ul>'; endif;
      //}
      //if ($show_messages && $messages): echo "<br><br>";print $messages; endif;
      $block[0]['content'] .= $help;
      //$block[0]['subject'] = t('New Module');
      break;
  }
  return $block[$delta];
}

/*Hook into the nodewords API to add googlebot tag with the same data as the robots tag*/
function custom_m2m_nodewords_api() {
  return array('version' => '1.13');
}

function custom_m2m_nodewords_tags_alter(&$output, $parameters) {
  if(isset($output['robots'])){
    $output['googlebot'] = $output['robots'];
  }
  if (empty($output['abstract']) && $parameters['type'] == NODEWORDS_TYPE_PAGE) {
    $output['abstract'] = t('Node content');
  }
}

function custom_m2m_form_content_field_edit_form_alter(&$form, &$form_state) {
  $form['#submit'][] = 'custom_m2m_content_field_edit_form_submit';
}

function custom_m2m_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'webform_client_form_677') {
    if (arg(0) == 'node' && is_numeric(arg(1)) && empty($form_state['post'])){
      $nodeid = arg(1);
      $node = node_load($nodeid);
      if(!isset($form['submitted']['subject']['#value']) || empty($form['submitted']['subject']['#value'])){
        $form['submitted']['subject']['#value'] = 'M2MSearch.com Inquiry: '.$node->title;
      }
      if(!isset($form['submitted']['vendor_email']['#value']) || empty($form['submitted']['vendor_email']['#value'])){
        switch($node->type){
          case 'connectivity_module':
            $contact_email = $node->field_conn_contact_email[0]['value'];
            break;
          case 'auto_module':
            $contact_email = $node->field_auto_contact_email[0]['value'];
            break;
          case 'device':
            $contact_email = $node->field_contact_email[0]['value'];
            break;
          case 'featured_product':
            $contact_email = $node->field_featured_contact_email[0]['value'];
            break;
          case 'router':
            $contact_email = $node->field_rout_contact_email[0]['value'];
            break;
        }
        if(isset($contact_email)){
          $form['submitted']['vendor_email']['#value'] = $contact_email;
        }
      }
    }
  }
  if ( $form_id == 'search_block_form' ) {
    //watchdog('falt', 'form_id : '. $form_id .' : <pre>'. print_r($form,true) .'</pre>');
    $form['search_block_form']['#title'] = t('Search Modules');
  }
}

/**
 * Implementation of hook_menu_alter().
 * Remember to clear the menu cache after adding/editing this function.
 */
function custom_m2m_menu_alter(&$items) {
  // Removing certain local navigation tabs that are either undesired or need to be custom relocated.

  // Set these tabs to MENU_CALLBACK, so they still register the path, but just don't show the tab:
  $items['user/%user/linkchecker']['type'] = MENU_CALLBACK;
}


function custom_m2m_content_field_edit_form_submit($form, &$form_state) {
  if(isset($form_state['#field_info']['field_company'])){
    if($form_state['#field_info']['field_company']['allowed_values'] != $form_state['values']['allowed_values']){
      $old_vals = explode("\r\n", $form_state['#field_info']['field_company']['allowed_values']);
      $new_vals = explode("\r\n", $form_state['values']['allowed_values']);
      $added_vals = array_diff($new_vals, $old_vals);
      if(!empty($added_vals)){
        $device_types = company_list_get_company_types();
        foreach($device_types as $t => $d){
          $companies_device = variable_get('m2m_company_list_'. $t, array());
          foreach($added_vals as $v){
            $companies_device[$v] = $v;
          }
          variable_set('m2m_company_list_' . $t, array_filter($companies_device));
        }
      }
    }
  }
}

function custom_m2m_nodewords_tags_info() {
  $tags = array(
    'googlebot' => array(
      'callback' => 'nodewords_basic_robots',
      'context' => array(
        'allowed' => array(
          NODEWORDS_TYPE_DEFAULT,
          NODEWORDS_TYPE_ERRORPAGE,
          NODEWORDS_TYPE_FRONTPAGE,
          NODEWORDS_TYPE_NODE,
          NODEWORDS_TYPE_OFFLINE,
          NODEWORDS_TYPE_PAGE,
          NODEWORDS_TYPE_PAGER,
          NODEWORDS_TYPE_TERM,
          NODEWORDS_TYPE_TRACKER,
          NODEWORDS_TYPE_USER,
          NODEWORDS_TYPE_VOCABULARY,
        ),
      ),
      'label' => t('Googlebot'),
      'permission' => 'edit meta tag ROBOTS',
      'templates' => array(
        'head' => array(
          'googlebot' => NODEWORDS_META,
        ),
      ),
    ),
  );

  return $tags;
}

/**
 * Implement hook_form_alter().
*/
function custom_m2m_form_user_admin_account_alter(&$form, $form_state) {
  if (!empty($form['name'])) {
    foreach (array_keys($form['name']) as $uid) {
      $profile = content_profile_load('profile', $uid, '', TRUE);
      $companies = array();
      foreach($profile->field_company as $c){
        $companies[] = $c['value'];
      }
      $form['company'][$uid]['#value'] = theme('item_list', $companies);
    }
  }
}